package engine.world.block.state;

import engine.world.block.Block;
import engine.world.block.state.property.Property;
import java.util.Collections;
import java.util.HashMap;
import java.util.Map;
import java.util.Objects;
import java.util.stream.Collectors;

public class BlockState {
    private final Block owner;
    private final Map<Property<?>, Comparable<?>> values;
    private int globalId = -1; // To be set by registry

    public BlockState(Block owner, Map<Property<?>, Comparable<?>> values) {
        this.owner = owner;
        this.values = values; // Should be immutable
    }

    public Block getBlock() {
        return owner;
    }

    public <T extends Comparable<T>> T get(Property<T> property) {
        Comparable<?> value = values.get(property);
        if (value == null) {
            throw new IllegalArgumentException("Cannot get property " + property + " as it does not exist in " + owner);
        }
        return property.getType().cast(value);
    }

    public <T extends Comparable<T>, V extends T> BlockState with(Property<T> property, V value) {
        if (!values.containsKey(property)) {
            throw new IllegalArgumentException("Cannot set property " + property + " as it does not exist in " + owner);
        }
        if (!property.getValues().contains(value)) {
            throw new IllegalArgumentException("Cannot set property " + property + " to " + value + " on block " + owner
                    + ", it is not an allowed value");
        }
        if (values.get(property).equals(value)) {
            return this;
        }

        // In a real optimized system, we would look up the neighbor state in a table
        // generated by StateDefinition
        // For now, we delegate back to owner's definition to find the peer state
        return owner.getStateDefinition().getStateWith(this, property, value);
    }

    public Map<Property<?>, Comparable<?>> getValues() {
        return Collections.unmodifiableMap(values);
    }

    public void setGlobalId(int id) {
        this.globalId = id;
    }

    public int getGlobalId() {
        return globalId;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(owner.getRegistryId() != null ? owner.getRegistryId().toString() : "unregistered");
        if (!values.isEmpty()) {
            sb.append("[");
            sb.append(values.entrySet().stream()
                    .map(e -> e.getKey().getName() + "=" + getName(e.getKey(), e.getValue()))
                    .collect(Collectors.joining(",")));
            sb.append("]");
        }
        return sb.toString();
    }

    @SuppressWarnings("unchecked")
    private <T extends Comparable<T>> String getName(Property<T> prop, Comparable<?> value) {
        return prop.name((T) value);
    }

    @Override
    public boolean equals(Object o) {
        if (this == o)
            return true;
        if (o == null || getClass() != o.getClass())
            return false;
        BlockState that = (BlockState) o;
        return Objects.equals(owner, that.owner) && Objects.equals(values, that.values);
    }

    @Override
    public int hashCode() {
        return Objects.hash(owner, values);
    }
}
